site_name: Digital Literacy Course
copyright: Copyright &copy; UBC A.R.T. and Justice

nav:
  - Home: index.md
  - Course: 
      - About Course: course/index.md
      - ✉️ Unit 1 | Communication: course/1-communication/index.md
      - 1.1 - Email: course/1-communication/1.1-email.md
      - 1.2 - Texting: course/1-communication/1.2-texting.md
      - 1.3 - Direct Messaging: course/1-communication/1.3-direct-message.md
      - 1.4 - Video Calls: course/1-communication/1.4-video-calls.md
      - 1.5 - Social Media: course/1-communication/1.5-social-media.md

      - 📂 Unit 2 | File Saving and Sharing: course/2-file-system/index.md
      - 2.1 - What is a file: course/2-file-system/2.1-files.md
      - 2.2 - How to save a file: course/2-file-system/2.2-saving-files.md
      - 2.3 - File Directories: course/2-file-system/2.3-directories.md

      - 🌎 Unit 3 | Staying Safe: course/5-staying-safe/index.md
      - 3.1 Updates: course/5-staying-safe/3.1-updates.md
      - 3.2 Passwords: course/5-staying-safe/3.2-passwords.md
      - 3.3 Encryption: course/5-staying-safe/3.3-encryption.md
      - 3.4 Viruses: course/5-staying-safe/3.4-viruses.md
      - 3.5 Internet Safety: course/5-staying-safe/3.5-internet-safety.md
  - About: about.md
  # - Internal:
  #     - Android: 
  #         - Device Setup: internal/android/device-setup.md
  #         - Reference: internal/android/reference.md
  #         - Other Notes: internal/android/other.md
  #     - Site Setup: 
  #         - Overview: internal/mkdocs-material/index.md
  #         - Initial Install: internal/mkdocs-material/install-and-setup.md
  #         - Configuration: internal/mkdocs-material/config.md
  #         - Blog Setup: internal/mkdocs-material/blog-setup-and-config.md
  #         - Blog Posts: internal/mkdocs-material/blog-make-post.md

plugins:
  - glightbox
  - search
  - privacy:
      enabled: !ENV [CI, false]
  - offline

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  language: en
  logo: assets/img/stack-of-books.png
  favicon: assets/img/stack-of-books.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select
  icon:
    repo: fontawesome/brands/github

extra:
  generator: false  # false: hides 'Generated with MkDocs' message in footer

extra_css:
  - assets/stylesheets/extra.css