site_name: Digital Literacy Course
copyright: Copyright &copy; UBC A.R.T. and Justice

nav:
  - Home: index.md
  - Course:
      - About Course: course/index.md

      - Introduction | The Technology Terror Experience: course/tech-terror-experience.md

      - 📱 Unit 1 | Navigating Your Tablet: course/1-tablet-navigation/index.md
      - 1.1 The Keyboard: course/1-tablet-navigation/1.1-the-keyboard.md
      - 1.2 Terminology: course/1-tablet-navigation/1.2-terminology.md

      - 🌎 Unit 2 | Apps and the Internet: course/2-apps-and-internet/index.md
      - 2.1 Connecting to the Internet: course/2-apps-and-internet/2.1-connecting-to-the-internet.md
      - 2.2 Navigating Websites: course/2-apps-and-internet/2.2-navigating-websites.md
      - 2.3 Browsers and Search Engines: course/2-apps-and-internet/2.3-browsers-and-search-engines.md
      - 2.4 Using Apps: course/2-apps-and-internet/2.4-using-apps.md
      - 2.5 Reputable Sources: course/2-apps-and-internet/2.5-reputable-sources.md

      - 📂 Unit 3 | File Saving and Sharing: course/3-file-system/index.md
      - 3.1 - What is a file: course/3-file-system/3.1-files.md
      - 3.2 - How to save a file: course/3-file-system/3.2-saving-files.md
      - 3.3 - File Directories: course/3-file-system/3.3-directories.md

      - 🔒 Unit 4 | Staying Safe: course/4-staying-safe/index.md
      - 4.1 Updates: course/4-staying-safe/4.1-updates.md
      - 4.2 Passwords: course/4-staying-safe/4.2-passwords.md
      - 4.3 Encryption: course/4-staying-safe/4.3-encryption.md
      - 4.4 Viruses: course/4-staying-safe/4.4-viruses.md
      - 4.5 Internet Safety: course/4-staying-safe/4.5-internet-safety.md

      - ✉️ Unit 5 | Communication: course/5-communication/index.md
      - 5.1 - Email: course/5-communication/5.1-email.md
      - 5.2 - Texting: course/5-communication/5.2-texting.md
      - 5.3 - Direct Messaging: course/5-communication/5.3-direct-message.md
      - 5.4 - Video Calls: course/5-communication/5.4-video-calls.md
      - 5.5 - Social Media: course/5-communication/5.5-social-media.md

      - Test Page 1: course/test-page-1.md
      - Test Page 2: course/test-page-2.md
  - About: about.md

plugins:
  - glightbox # for images
  - search # for search
  - privacy: # for loading foreign content
      enabled: !ENV [CI, false]
  - offline # for offline support

markdown_extensions:
  - admonition # for callout boxes
  - attr_list # allows HTML attributes in markdown
  - md_in_html # for markdown in HTML
  - pymdownx.details # makes callout boxes interactive
  - pymdownx.superfences: # support for diagrams
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - sane_lists # python-markdown.github.io/extensions/sane_lists/
  - pymdownx.emoji: # for using icons
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  language: en
  logo: assets/img/stack-of-books.png
  favicon: assets/img/stack-of-books.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
    #   toggle:
    #     icon: material/weather-sunny
    #     name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: black
    #   accent: indigo
    #   toggle:
    #     icon: material/weather-night
    #     name: Switch to system preference
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select

extra:
  generator: false # false: hides 'Generated with MkDocs' message in footer

extra_css:
  - assets/stylesheets/extra.css
